use std::str::FromStr;
use crate::ast;

grammar;

Label: String = <s:r"[a-zA-Z_-][a-zA-Z0-9_-]+"> => s.to_string();
Num: i64 = <s:r"[0-9]+"> => i64::from_str(s).unwrap();
Bool: bool = {
    "true" => true,
    "false" => false
};

pub Term: Box<ast::Expr> = {
    Literal => Box::new(ast::Expr::Literal(<>)),
    "(" <e:Expr> ")" => e,
}

pub Expr: Box<ast::Expr> = {
    #[precedence(level="1")]
    Term,

    #[precedence(level="2")] #[assoc(side="left")]
    UnOp Expr => Box::new(ast::Expr::UnExp(<>)),

    #[precedence(level="3")] #[assoc(side="left")]
    Expr ExponentBinOp Expr => Box::new(ast::Expr::BinExp(<>)),

    #[precedence(level="4")] #[assoc(side="left")]
    Expr FactorBinOp Expr => Box::new(ast::Expr::BinExp(<>)),

    #[precedence(level="5")] #[assoc(side="left")]
    Expr TermBinOp Expr => Box::new(ast::Expr::BinExp(<>)),

    #[precedence(level="6")] #[assoc(side="left")]
    Expr ComparisonBinOp Expr => Box::new(ast::Expr::BinExp(<>)),

    #[precedence(level="7")] #[assoc(side="left")]
    Expr BoolBinOp Expr => Box::new(ast::Expr::BinExp(<>)),
};

TermBinOp: ast::BinOp = {
    "+" => ast::BinOp::Add,
    "-" => ast::BinOp::Sub,
};

FactorBinOp: ast::BinOp = {
    "*" => ast::BinOp::Mul,
    "/" => ast::BinOp::Div,
    "%" => ast::BinOp::Mod,
};

ExponentBinOp: ast::BinOp = {
    "**" => ast::BinOp::Pow
};

ComparisonBinOp: ast::BinOp = {
    "<" => ast::BinOp::Lt,
    ">" => ast::BinOp::Gt,
    "<=" => ast::BinOp::Leq,
    ">=" => ast::BinOp::Geq,
    "==" => ast::BinOp::Eq,
    "!=" => ast::BinOp::Neq,
};

BoolBinOp: ast::BinOp = {
    "&&" => ast::BinOp::And,
    "||" => ast::BinOp::Or,
    "^" => ast::BinOp::XOr,
};

UnOp: ast::UnOp = {
    "!" => ast::UnOp::Not,
    "-" => ast::UnOp::Neg,
};

pub Literal: ast::Literal = {
    Num => ast::Literal::Integer(<>),
    Bool => ast::Literal::Boolean(<>)
};

LVar: ast::LVar = {
    
};

Id: ast::Id = Label => ast::Id(<>);

TypeList: Vec<ast::Type> = {
    <t:Type> => Vec::from([t]),
    <mut l:TypeList> "," <t:Type> => {
        l.push(t);
        l
    }
}

Type: ast::Type = {
    "unit" => ast::Type::Unit,
    "int" => ast::Type::Integer,
    "bool" => ast::Type::Boolean,
    "&" <typ:Type> => ast::Type::Ref(Box::new(typ)),
    "Fn" "(" <ts:TypeList> ")" "->" <r:Type> => ast::Type::Fun { args: ts, ret: Box::new(r) },
};

pub Stmt: ast::Stmt = {
    "var" <i:Id> => ast::Stmt::Var(i, None),
    "var" <i:Id> ":" <typ:Type> => ast::Stmt::Var(i, Some(typ))
};
